fix always send UTC format to API (#5)
* fix always send UTC format to API

When requesting stream campaign_stats_daily, I always got the error

Exception: 400, E1004: Invalid query parameters in request URL: [Invalid StartDateTime: 2020-06-17T00:00:00 0200]

My account is running on Europe/Berlin timezone. The API can not handle the timezone +0200 time extension. With this change, the timezone will be send to the API in UTC.

* added raise-missing-from to pylint disables

Co-authored-by: Leonhard Schick <leonhard.schick@horze.com>
Co-authored-by: Zach Harris <zharris@talend.com>
Co-authored-by: Collin Simon <cosimon@users.noreply.github.com>